### ISSUE TITLE
Running pnpm install

### ISSUE THREAD

**Issue by rwollgar** [kirankunigiri/vite-plugin-react-control-statements#1] opened 2024-06-17 22:16 UTC
pnpm install generates an error and I don't understand what the problem is.
I cloned the repo and ran pnpm install

I tried running from the example directory and the root directory but I am getting the same error.

$ pnpm install
Scope: all 2 workspace projects
C:\gitrepos\playground\vite-plugin-react-control-statements\example:
 ERR_PNPM_WORKSPACE_PKG_NOT_FOUND  In example: "@types/vite-plugin-react-control-statements@workspace:*" is in the dependencies but no package named "@types/vite-plugin-react-control-statements" is present in the workspace

This error happened while installing a direct dependency of C:\gitrepos\playground\vite-plugin-react-control-statements\example

Packages found in the workspace: example, vite-plugin-react-control-statements
Progress: resolved 0, reused 1, downloaded 0, added 0

**Comment by kirankunigiri** [comment] 2024-06-17 22:26
Thanks for bringing this up, I realized what the error is. I was previously using a folder called "@types/vite-plugin-react-control-statements" to simulate a @ types package and make sure types work, and later deleted it because I didn't need it. I'll fix this and comment again when it's ready.

**Comment by kirankunigiri** [comment] 2024-06-17 22:30
I've fixed the issue in the latest commit. Please pull the changes and let me know if the issue is fixed, thanks!

**Comment by rwollgar** [comment] 2024-06-17 23:20
Hi Kiran,

pnpm install works fine now.
I've been waiting for jsx-control-statements support in vite for quite a while. The missing support stopped me from trying out vite.
I am using webpack+babel right now and I make extensive use of jsx-control-statements.

Thank you for making this plugin available.

BTW I am only using if/choose/when/otherwise not the For/With tags because I am used to the .map() pattern and find it readable enough in jsx code.

Kind regards
Rainer Wollgarten

**Comment by kirankunigiri** [comment] 2024-06-17 23:35
That's great to hear, thanks for using my project! Closing this issue now.

**Closed as completed by kirankunigiri** 2024-06-17 23:35 UTC
